#!/usr/bin/env bash

set -e

tags="$1"

if [ -z $tags ]; then
  tags="all"
fi

## Install ansible if not already installed
if ! [ -x "$(command -v ansible)" ]; then
  sudo apt-get install -y ansible
fi


# Check if vault.key exists
if [ ! -f ~/vault.key ]; then
  echo "Error: vault.key file not found! Ansible vault password is required."
  exit 1
fi

## Run ansible
# ansible-playbook -t core,dotfiles --ask-become-pass --vault-password-file ~/vault.key local.yaml
ansible-pull -U https://github.com/tanishqmanuja/devenv.git -t core,dotfiles --ask-become-pass --vault-password-file ~/vault.key