#!/usr/bin/env bash

set -e

tags="$1"

if [ -z $tags ]; then
  tags="core,dotfiles"
fi

## Install ansible if not already installed
if ! [ -x "$(command -v ansible)" ]; then
  echo "==== Installing ansible ====\n"
  sudo apt-add-repository -y ppa:ansible/ansible
  sudo apt-get update -y
  sudo apt-get install -y ansible
fi

## Install neovim (latest) if not already installed
if ! [ -x "$(command -v nvim)" ]; then
  echo "==== Installing neovim ====\n"
  sudo apt-add-repository -y ppa:neovim-ppa/unstable
  sudo apt-get update -y
  sudo apt-get install -y neovim
fi

# Check if vault.key exists
if [ ! -f ~/vault.key ]; then
  echo "Error: vault.key file not found! Ansible vault password is required."
  exit 1
fi

## Run ansible
echo "==== Running ansible-pull ====\n"
ansible-pull -U https://github.com/tanishqmanuja/devenv.git -t $tags --ask-become-pass --vault-password-file ~/vault.key
