- hosts: localhost

  pre_tasks:
  - name: Update apt cache
    become: true
    apt: 
      update_cache: yes
    tags:
      - install
      - core

  tasks:
    - import_tasks: tasks/ssh.yaml
    - import_tasks: tasks/git.yaml
    - import_tasks: tasks/core.yaml
    - import_tasks: tasks/asdf.yaml
    - import_tasks: tasks/starship.yaml
    - import_tasks: tasks/dotfiles.yaml
    - import_tasks: tasks/nvim.yaml