---

- name: Install Packages 1 (python3-pip, python3-venv)
  become: true
  apt:
    name:
      - python3-pip
      - python3-venv
    state: present
  tags:
    - install
    - core
    - neovim
    - nvim

- name: Install Packages 2 (zsh, tmux)
  become: true
  apt:
    name:
      - zsh
      - tmux
    state: present
  tags:
    - install
    - core