---

- name: Install Packages 1 (curl, unzip, cmake, build-essential)
  become: true
  apt:
    name:
      - curl
      - unzip
      - cmake
      - build-essential
    state: present
  tags:
    - install
    - core
    - neovim
    - nvim

- name: Install Packages 2 (python3-pip, python3-venv)
  become: true
  apt:
    name:
      - python3-pip
      - python3-venv
    state: present
  tags:
    - install
    - core
    - neovim
    - nvim

- name: Install Packages 3 (fzf, bat, ripgrep)
  become: true
  apt:
    name:
      - fzf
      - bat
      - ripgrep
    state: present
  tags:
    - install
    - core

- name: Install exa
  become: true
  apt:
    name:
      - exa
    state: present
  when: ansible_distribution_version | float >= 20.10
  tags:
    - install
    - core

