---

- name: Add a setting to ~/.gitconfig
  git_config:
    name: init.defaultBranch
    scope: global
    value: main
  tags:
  - git

- name: Add a setting to ~/.gitconfig
  git_config:
    name: pull.rebase
    scope: global
    value: true
  tags:
  - git

- name: Git setup for tanishqmanuja
  git_config:
    name: include.path
    scope: global
    value: "~/.gitconfigs/tanishqmanuja.gitconfig"
  tags:
  - git
