---

- name: Install prerequisites (lazygit)
  become: true
  apt:
    name:
      - curl
      - jq
    state: present
  tags: &tags_for_lazygit_task
    - install
    - core
    - lazygit

- name: Get latest lazygit version
  shell: "curl -s 'https://api.github.com/repos/jesseduffield/lazygit/releases/latest' | jq -r '.tag_name[1:]'"
  register: lazygit_version
  tags: *tags_for_lazygit_task

- name: Download lazygit tarball
  shell: curl -Lo /tmp/lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ lazygit_version.stdout }}_Linux_x86_64.tar.gz"
  tags: *tags_for_lazygit_task

- name: Extract lazygit tarball
  shell: "tar xf /tmp/lazygit.tar.gz -C /tmp lazygit"
  tags: *tags_for_lazygit_task

- name: Install lazygit
  become: true
  shell: "cd /tmp && sudo install lazygit /usr/local/bin"
  tags: *tags_for_lazygit_task

- name: Clean up
  file:
    path: /tmp/lazygit.tar.gz
    state: absent
  tags: *tags_for_lazygit_task