---

- name: Install prerequisites (lazygit)
  become: true
  apt:
    name:
      - curl
      - jq
    state: present
  tags: &tags_for_lazygit_task
    - install
    - core
    - lazygit

- name: Get latest lazygit version
  shell: "curl -s 'https://api.github.com/repos/jesseduffield/lazygit/releases/latest' | jq -r '.tag_name[1:]'"
  register: lazygit_version
  tags: *tags_for_lazygit_task

- name: Download lazygit tarball
  get_url:
    url: "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ lazygit_version.stdout }}_Linux_x86_64.tar.gz"
    dest: /tmp/lazygit.tar.gz
  tags: *tags_for_lazygit_task

- name: Extract lazygit archive
  unarchive:
    src: /tmp/lazygit.tar.gz
    dest: /tmp
    extra_opts: ['--strip', '1']
  tags: *tags_for_lazygit_task

- name: Install lazygit
  become: true
  command: sudo install lazygit /usr/local/bin
  args:
    chdir: /tmp
  tags: *tags_for_lazygit_task

- name: Clean up
  file:
    path: /tmp/lazygit.tar.gz
    state: absent
  tags: *tags_for_lazygit_task