---

- name: Ensure .ssh directory exists
  file:
    path: .ssh
    state: directory
    mode: 0700
  tags: &tags_for_ssh_task
    - dotfiles
    - install
    - ssh

- name: Install ssh keys
  copy:
    src: .ssh
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    mode: 0600
  tags: *tags_for_ssh_task