---

- name: Download zoxide installation script
  get_url:
    url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh
    dest: /tmp/zoxide_install.sh
    mode: 0755
  tags: &tags_for_zoxide_task
  - install
  - core
  - zoxide

- name: Install zoxide using downloaded script
  shell: /tmp/zoxide_install.sh
  tags: *tags_for_zoxide_task