- name: Install zsh
  become: true
  apt:
    name: zsh
    state: present
  tags: &tags_for_zsh_task
    - install
    - core
    - zsh

- name: Change shell to zsh
  command: usermod --shell /bin/zsh {{ ansible_env.USER }}
  become: true
  tags: *tags_for_zsh_task